---
connection:
  downstream:
    readTimeoutSeconds: 5
    roundTripTimeoutSeconds: 120
    idleTimeoutSeconds: 30
    maxBodyBytes: 1048576
    http:
      port: 80
    {{ .TLS }}

  upstream:
    socketTimeoutSeconds: 3
    readTimeoutSeconds: 120
    idleTimeoutSeconds: 10
    #inside kube this must always be true
    tlsInsecureSkipVerify: true

routes:
  {{ .ROUTES }}

resources:
  {{ .RESOURCES }}
