kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrole-ingress-j8a
rules:
  - apiGroups: [""]
    resources: ["secrets", "services", "ingress", "configmaps", "roles", "rolebindings", "serviceaccounts"]
    verbs: ["get", "list", "watch"]