kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrolebinding-ingress-j8a
subjects:
  - kind: ServiceAccount
    name: serviceaccount-ingress-j8a
    namespace: default
roleRef:
  kind: ClusterRole
  name: clusterrole-ingress-j8a
  apiGroup: rbac.authorization.k8s.io