kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrole-ingress-j8a
rules:
  - apiGroups: [""]
    resources: ["secrets", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ "services", "deployments", "replicasets", "pods" ]
    verbs: [ "*" ]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: [ "ingresses" ]
    verbs: [ "get", "list", "watch" ]